# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: key-dev-jdk8

cache:
  paths:
    - .m2/
    - .gradle/

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GIT_SSL_NO_VERIFY: "true"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
#  - export GRADLE_OPTS="-Dorg.gradle.daemon=false --add-modules java.xml.bind '-Dorg.gradle.jvmargs=--add-modules java.xml.bind'"


stages:
  - build
  - test
  - deploy

build:jdk8:
  stage: build
  variables:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  script: gradle --build-cache assemble
  image: key-dev-jdk8

  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: gradle check
  allow_failure: true
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

deploy:
  stage: deploy
  script: gradle distJar
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - "build/libs/*.jar"
  allow_failure: true
