image: maven:3.5.0-jdk-8



build:
  script: "mvn compile -B -T 2"


test: 
  dependencies:
    - build
  script: "mvn test -B"

package: 
  dependencies:
    - test
  script: "mvn package -DskiptTests=true -B"
  

doc: 
  dependencies:
    - test
  script: "mvn site:site -DskiptTests=true -B"