image: maven:3.5.0-jdk-8



build:
  script: "mvn compile -B -T 2"


test: 
  script: "mvn test -B"

deploy:
  script: 
    - "mvn package site:site -DskiptTests=true -B"
  artifacts: 
    paths:
      - target/*jar
      - target/site/*