image: key-ant-openjdk-8:latest




cache:
  paths:
    - .m2/

variables:
  MAVEN_OPTS: -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SSL_NO_VERIFY: "true"

  

build:
  script: "mvn compile -B -T 2"


test: 
  script: "mvn test -B"

deploy:
  script: 
    - "mvn package site:site -DperformRelease=true -DcreateChecksum=true -DskipTests=true -B"
  artifacts: 
    paths:
      - target/*jar
      - target/site/*
  allow_failure: true