image: key-ant-openjdk-8:latest

cache:
  paths:
    - .m2/

variables:
  MAVEN_OPTS: >-
    -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
  GIT_SSL_NO_VERIFY: "true"

stages:
  - setup
  - build
  - test
  - deploy

setup:
  script: >
    COMPONENTS=keydeps/lib/components/
    mvn install:install-file -Dfile=$COMPONENTS/key.core.jar \
                               -DgroupId=key-project-psdbg \
                               -DartifactId=key.core \
                               -Dversion=2.7-SNAPSHOT \
                               -Dpackaging=jar

    mvn install:install-file -Dfile=$COMPONENTS/key.ui.jar \
                               -DgroupId=key-project-psdbg \
                               -DartifactId=key.ui \
                               -Dversion=2.7-SNAPSHOT \
                               -Dpackaging=jar

    mvn install:install-file -Dfile=$COMPONENTS/key.util.jar \
                               -DgroupId=key-project-psdbg \
                               -DartifactId=key.util \
                               -Dversion=2.7-SNAPSHOT \
                               -Dpackaging=jar

    mvn install:install-file -Dfile=$COMPONENTS/../libs/recoderKey.jar\
                               -DgroupId=key-project-psdbg \
                               -DartifactId=recoder \
                               -Dversion=2.7\
                               -Dpackaging=jar


build:
  stage: build
  script: "mvn compile -B -T 2"

test:
  stage: test
  script: "mvn test -B"

deploy:
  stage: deploy
  script: 
    - "mvn package -DperformRelease=true -DcreateChecksum=true -DskipTests=true -B"
  artifacts: 
    paths:
      - target/*jar
      - target/site/*
  allow_failure: true