site_name: Proof Script Debugger -- KeY
site_url: https://formal.iti.kit.edu/psdbg
#weigl/verifaps/
#repo_url: https://github.com/example/repository/
site_description:
site_author: Sarah Grebing <sarah.grebing@kit.edu>, Alexander Weigl <weigl@kit.edu>


theme_dir: kit_theme

markdown_extensions:
  - fenced_code
  - codehilite
  - footnotes
  - smarty
  - toc:
      permalink: True
      separator: "_"
  - sane_lists
    #  - mdx_math:
    #  enable_dollar_delimiter: True #for use of inline $..$

    #extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']

